version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  service:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    command: run
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
